<script setup lang="ts">
import type { BugReport } from '~/composables/useBugs'
import { formatDateTime } from '~/utils/presentation'

const props = defineProps<{ bugs: BugReport[]; group: 'action' | 'waiting' | 'closed'; pendingId: string | null; stale: boolean; rowErrors: Record<string, string> }>()
const emit = defineEmits<{ start: [bug: BugReport]; resume: [bug: BugReport] }>()
const latestAttempt = (bug: BugReport) => [...bug.resolution_attempts].sort((left, right) => right.attempt_number - left.attempt_number)[0]
const resumable = (bug: BugReport) => { const attempt = latestAttempt(bug); return bug.status === 'reopened' && bug.allowed_actions.includes('resume_work') && attempt?.outcome === 'fixed' && attempt.qa_result?.decision === 'rejected' }
const startable = (bug: BugReport) => bug.status === 'assigned' && bug.allowed_actions.includes('start_work')
const detailTarget = (bug: BugReport) => `/bugs/${encodeURIComponent(bug.public_id)}`
function handoff(bug: BugReport): string {
  if (resumable(bug)) return 'ردشده در QA؛ آمادهٔ ادامهٔ کار'
  if (startable(bug)) return 'آمادهٔ شروع کار'
  if (bug.status === 'in_progress') return 'در حال انجام؛ ثبت پیشرفت یا نتیجهٔ رفع در جزئیات'
  if (bug.status === 'qa_verification') return bug.active_resolution ? `در انتظار تصمیم QA · ${outcomeLabel(bug.active_resolution.outcome)}` : 'در انتظار تصمیم QA'
  if (bug.status === 'reopened') return 'در انتظار بازگشت به بررسی مدیر'
  if (bug.status === 'review') return 'در انتظار اقدام مدیر'
  if (bug.status === 'needs_information') return 'در انتظار پاسخ گزارش‌دهنده'
  if (bug.status === 'submitted') return 'در انتظار آغاز بررسی'
  if (bug.status === 'resolved') return 'اقدام توسعه‌دهنده در این وضعیت در دسترس نیست'
  if (bug.status === 'closed') return bug.active_resolution?.qa_result?.decision === 'approved' ? 'تأییدشده در QA؛ تخصیص تاریخی' : 'تخصیص تاریخی بسته‌شده'
  return 'اقدام توسعه‌دهنده در این وضعیت در دسترس نیست'
}
function outcomeLabel(outcome: string) { return ({ fixed: 'رفع ثبت شده', duplicate: 'تکراری', cannot_reproduce: 'قابل بازتولید نیست', wont_fix: 'رفع نخواهد شد' } as Record<string, string>)[outcome] || outcome }
</script>

<template>
  <div class="developer-ledger">
    <table class="developer-ledger__table"><thead><tr><th>باگ</th><th>پروژه</th><th>اولویت / شدت</th><th>وضعیت و گام بعد</th><th>آخرین به‌روزرسانی باگ</th><th><span class="sr-only">اقدام</span></th></tr></thead><tbody><tr v-for="bug in bugs" :key="bug.id"><td><NuxtLink :id="`developer-bug-${bug.id}`" class="developer-ledger__bug" :to="detailTarget(bug)"><span dir="auto">{{ bug.title }}</span><TechnicalValue :value="bug.public_id" /></NuxtLink></td><td><ProjectIdentity :name="bug.project.name" :project-key="bug.project.key" /><UBadge v-if="!bug.project.active" color="warning" variant="subtle" class="developer-ledger__inactive">پروژه غیرفعال</UBadge></td><td><span class="developer-ledger__classification"><small>اولویت</small>{{ bug.priority?.name || 'تعیین‌نشده' }}<small>شدت</small>{{ bug.severity?.name || 'تعیین‌نشده' }}</span></td><td><div class="developer-ledger__state"><BugStatusBadge :status="bug.status" /><span>{{ handoff(bug) }}</span></div><p v-if="rowErrors[bug.id]" class="developer-ledger__error" role="alert">{{ rowErrors[bug.id] }}</p></td><td><time :datetime="bug.updated_at">{{ formatDateTime(bug.updated_at) }}</time></td><td><UButton v-if="group === 'action' && startable(bug)" size="sm" :loading="pendingId === bug.id" :disabled="stale || !!pendingId" :aria-label="`شروع کار برای ${bug.public_id}`" @click="emit('start', bug)">شروع کار</UButton><UButton v-else-if="group === 'action' && resumable(bug)" size="sm" :loading="pendingId === bug.id" :disabled="stale || !!pendingId" :aria-label="`ادامهٔ کار برای ${bug.public_id}`" @click="emit('resume', bug)">ادامهٔ کار</UButton><UButton v-else-if="bug.project.active" :to="detailTarget(bug)" size="sm" color="neutral" variant="outline">{{ group === 'action' ? 'باز کردن محیط کار' : 'مشاهدهٔ جزئیات' }}</UButton><span v-else class="developer-ledger__unavailable">پروژه غیرفعال</span></td></tr></tbody></table>
    <ol class="developer-ledger__mobile"><li v-for="bug in bugs" :key="bug.id"><NuxtLink :id="`developer-mobile-bug-${bug.id}`" class="developer-ledger__bug" :to="detailTarget(bug)"><span dir="auto">{{ bug.title }}</span><TechnicalValue :value="bug.public_id" /></NuxtLink><div class="developer-ledger__mobile-meta"><ProjectIdentity :name="bug.project.name" :project-key="bug.project.key" /><BugStatusBadge :status="bug.status" /></div><p class="developer-ledger__classification">اولویت: {{ bug.priority?.name || 'تعیین‌نشده' }} · شدت: {{ bug.severity?.name || 'تعیین‌نشده' }}</p><p class="developer-ledger__handoff">{{ handoff(bug) }}</p><time :datetime="bug.updated_at">آخرین به‌روزرسانی باگ: {{ formatDateTime(bug.updated_at) }}</time><p v-if="rowErrors[bug.id]" class="developer-ledger__error" role="alert">{{ rowErrors[bug.id] }}</p><UButton v-if="group === 'action' && startable(bug)" block :loading="pendingId === bug.id" :disabled="stale || !!pendingId" @click="emit('start', bug)">شروع کار</UButton><UButton v-else-if="group === 'action' && resumable(bug)" block :loading="pendingId === bug.id" :disabled="stale || !!pendingId" @click="emit('resume', bug)">ادامهٔ کار</UButton><UButton v-else-if="bug.project.active" :to="detailTarget(bug)" block color="neutral" variant="outline">{{ group === 'action' ? 'باز کردن محیط کار' : 'مشاهدهٔ جزئیات' }}</UButton><span v-else class="developer-ledger__unavailable">پروژه غیرفعال</span></li></ol>
  </div>
</template>

<style scoped>
.developer-ledger{border-top:1px solid var(--ui-border)}.developer-ledger__table{border-collapse:collapse;table-layout:fixed;width:100%}.developer-ledger__table th{color:var(--ui-text-muted);font-size:.72rem;font-weight:650;padding:.65rem .75rem;text-align:start}.developer-ledger__table td{border-top:1px solid var(--ui-border);font-size:.82rem;padding:.8rem .75rem;vertical-align:top}.developer-ledger__table th:nth-child(1){width:25%}.developer-ledger__table th:nth-child(2){width:15%}.developer-ledger__table th:nth-child(3){width:13%}.developer-ledger__table th:nth-child(4){width:27%}.developer-ledger__table th:nth-child(5){width:12%}.developer-ledger__table th:nth-child(6){width:8%}.developer-ledger__bug{color:var(--ui-text-highlighted);display:grid;font-weight:650;gap:.2rem;line-height:1.5;text-decoration:none}.developer-ledger__bug:hover span:first-child{text-decoration:underline;text-underline-offset:.2rem}.developer-ledger__bug :deep(bdi){color:var(--ui-text-muted);font-size:.74rem;font-weight:400}.developer-ledger__inactive{margin-top:.35rem}.developer-ledger__classification{display:grid;gap:.1rem}.developer-ledger__classification small{color:var(--ui-text-muted);font-size:.68rem}.developer-ledger__state{display:grid;gap:.35rem}.developer-ledger__state>span,.developer-ledger__handoff{color:var(--ui-text-muted);line-height:1.55;margin:0}.developer-ledger__error{color:var(--ui-error);font-size:.75rem;margin:.45rem 0 0}.developer-ledger__unavailable{color:var(--ui-text-dimmed);font-size:.76rem}.developer-ledger__table time,.developer-ledger__mobile time{color:var(--ui-text-muted);font-size:.74rem;white-space:nowrap}.developer-ledger__mobile{display:none}.developer-ledger__mobile-meta{align-items:center;display:flex;flex-wrap:wrap;gap:.5rem}.developer-ledger__mobile li{border-top:1px solid var(--ui-border);display:grid;gap:.55rem;list-style:none;padding:1rem 0}@media(max-width:767px){.developer-ledger__table{display:none}.developer-ledger__mobile{display:grid;margin:0;padding:0}.developer-ledger__classification{color:var(--ui-text-muted);font-size:.78rem}.developer-ledger__mobile :deep(button),.developer-ledger__mobile :deep(a[class*=button]){min-height:2.75rem}}
</style>
