<script setup lang="ts">
import type { BugReport, ResolutionAttempt } from '~/composables/useBugs'
import { formatDateTime, formatNumber } from '~/utils/presentation'

const props = defineProps<{ bugs: BugReport[]; actionable?: boolean; inconsistent?: boolean }>()

function detailTarget(bug: BugReport) { return `/bugs/${encodeURIComponent(bug.public_id)}` }
function attemptFor(bug: BugReport): ResolutionAttempt | null { return bug.active_resolution }
function isDuplicate(attempt: ResolutionAttempt | null) { return attempt?.outcome === 'duplicate' }
function reviewActionLabel(bug: BugReport) { return props.actionable && attemptFor(bug) ? 'بررسی و ثبت تصمیم' : 'مشاهده جزئیات' }
function missing(value: string | null | undefined, label: string) { return value || `${label} در دسترس نیست` }
</script>

<template>
  <div class="qa-ledger">
    <table class="qa-ledger__table">
      <thead><tr><th>باگ</th><th>پروژه</th><th class="qa-ledger__classification-column">طبقه‌بندی</th><th>تلاش</th><th>زمینهٔ بررسی</th><th>ارسال برای QA</th><th><span class="sr-only">اقدام</span></th></tr></thead>
      <tbody>
        <tr v-for="bug in bugs" :key="bug.id">
          <td><BugIdentityLink :id="`qa-bug-${bug.id}`" :public-id="bug.public_id" :title="bug.title" :to="detailTarget(bug)" /></td>
          <td><ProjectIdentity :name="bug.project.name" :project-key="bug.project.key" /><p class="qa-ledger__classification qa-ledger__classification--compact">اولویت: {{ bug.priority?.name || 'تعیین‌نشده' }}<br>شدت: {{ bug.severity?.name || 'تعیین‌نشده' }}</p></td>
          <td class="qa-ledger__classification-column"><p class="qa-ledger__classification"><span>اولویت</span>{{ bug.priority?.name || 'تعیین‌نشده' }}<span>شدت</span>{{ bug.severity?.name || 'تعیین‌نشده' }}</p></td>
          <td><div v-if="attemptFor(bug)" class="qa-ledger__attempt"><ResolutionOutcomeBadge :outcome="attemptFor(bug)!.outcome" /><span>تلاش {{ formatNumber(attemptFor(bug)!.attempt_number) }}</span><UserIdentity :name="attemptFor(bug)!.recorded_by.display_name" :active="attemptFor(bug)!.recorded_by.active" compact /></div><span v-else class="qa-ledger__warning">تلاش فعال در دسترس نیست</span><p v-if="inconsistent" class="qa-ledger__warning qa-ledger__row-warning">صلاحیت یا وضعیت نیازمند به‌روزرسانی است</p></td>
          <td><div v-if="attemptFor(bug)" class="qa-ledger__context"><p><span>توضیحات</span><bdi dir="auto">{{ missing(attemptFor(bug)!.explanation, 'توضیحات') }}</bdi></p><p v-if="attemptFor(bug)!.outcome === 'fixed'" :class="{ 'qa-ledger__warning': !attemptFor(bug)!.qa_instructions }"><span>دستورالعمل QA</span><bdi dir="auto">{{ missing(attemptFor(bug)!.qa_instructions, 'دستور بررسی') }}</bdi></p><template v-else-if="attemptFor(bug)!.outcome === 'cannot_reproduce'"><p :class="{ 'qa-ledger__warning': !attemptFor(bug)!.reproduction_attempts }"><span>مراحل امتحان‌شده</span><bdi dir="auto">{{ missing(attemptFor(bug)!.reproduction_attempts, 'مراحل امتحان‌شده') }}</bdi></p><p :class="{ 'qa-ledger__warning': !attemptFor(bug)!.reproduction_environment }"><span>محیط بازتولید</span><bdi dir="auto">{{ missing(attemptFor(bug)!.reproduction_environment, 'محیط بازتولید') }}</bdi></p></template><p v-else-if="attemptFor(bug)!.outcome === 'wont_fix'" :class="{ 'qa-ledger__warning': !attemptFor(bug)!.decision_rationale }"><span>توجیه تصمیم</span><bdi dir="auto">{{ missing(attemptFor(bug)!.decision_rationale, 'توجیه تصمیم') }}</bdi></p><p v-else-if="isDuplicate(attemptFor(bug))" class="qa-ledger__duplicate"><span>رابطهٔ تکراری</span><bdi dir="auto">برای بررسی رابطهٔ فعال به جزئیات باگ بروید؛ این رابطه به تلاش مشخصی متصل نیست.</bdi></p></div><span v-else class="qa-ledger__warning">زمینهٔ بررسی نیازمند به‌روزرسانی است</span></td>
          <td><time v-if="attemptFor(bug)" :datetime="attemptFor(bug)!.recorded_at">{{ formatDateTime(attemptFor(bug)!.recorded_at) }}</time><span v-else>—</span></td>
          <td><UButton :to="detailTarget(bug)" color="neutral" :variant="actionable ? 'outline' : 'ghost'" size="sm" :aria-label="`${reviewActionLabel(bug)} برای ${bug.public_id}`">{{ reviewActionLabel(bug) }}</UButton></td>
        </tr>
      </tbody>
    </table>
    <ol class="qa-ledger__mobile"><li v-for="bug in bugs" :key="bug.id"><BugIdentityLink :id="`qa-mobile-bug-${bug.id}`" :public-id="bug.public_id" :title="bug.title" :to="detailTarget(bug)" /><ProjectIdentity :name="bug.project.name" :project-key="bug.project.key" /><p class="qa-ledger__mobile-classification">اولویت: {{ bug.priority?.name || 'تعیین‌نشده' }} · شدت: {{ bug.severity?.name || 'تعیین‌نشده' }}</p><template v-if="attemptFor(bug)"><div class="qa-ledger__attempt"><ResolutionOutcomeBadge :outcome="attemptFor(bug)!.outcome" /><span>تلاش {{ formatNumber(attemptFor(bug)!.attempt_number) }}</span><UserIdentity :name="attemptFor(bug)!.recorded_by.display_name" :active="attemptFor(bug)!.recorded_by.active" compact /></div><p v-if="inconsistent" class="qa-ledger__warning qa-ledger__row-warning">صلاحیت یا وضعیت نیازمند به‌روزرسانی است</p><div class="qa-ledger__context"><p><span>توضیحات</span><bdi dir="auto">{{ missing(attemptFor(bug)!.explanation, 'توضیحات') }}</bdi></p><p v-if="attemptFor(bug)!.outcome === 'fixed'" :class="{ 'qa-ledger__warning': !attemptFor(bug)!.qa_instructions }"><span>دستورالعمل QA</span><bdi dir="auto">{{ missing(attemptFor(bug)!.qa_instructions, 'دستور بررسی') }}</bdi></p><template v-else-if="attemptFor(bug)!.outcome === 'cannot_reproduce'"><p :class="{ 'qa-ledger__warning': !attemptFor(bug)!.reproduction_attempts }"><span>مراحل امتحان‌شده</span><bdi dir="auto">{{ missing(attemptFor(bug)!.reproduction_attempts, 'مراحل امتحان‌شده') }}</bdi></p><p :class="{ 'qa-ledger__warning': !attemptFor(bug)!.reproduction_environment }"><span>محیط بازتولید</span><bdi dir="auto">{{ missing(attemptFor(bug)!.reproduction_environment, 'محیط بازتولید') }}</bdi></p></template><p v-else-if="attemptFor(bug)!.outcome === 'wont_fix'" :class="{ 'qa-ledger__warning': !attemptFor(bug)!.decision_rationale }"><span>توجیه تصمیم</span><bdi dir="auto">{{ missing(attemptFor(bug)!.decision_rationale, 'توجیه تصمیم') }}</bdi></p><p v-else-if="isDuplicate(attemptFor(bug))" class="qa-ledger__duplicate"><span>رابطهٔ تکراری</span><bdi dir="auto">برای بررسی رابطهٔ فعال به جزئیات باگ بروید؛ این رابطه به تلاش مشخصی متصل نیست.</bdi></p></div><time :datetime="attemptFor(bug)!.recorded_at">ارسال برای QA: {{ formatDateTime(attemptFor(bug)!.recorded_at) }}</time></template><p v-else class="qa-ledger__warning">تلاش فعال در دسترس نیست؛ جزئیات باگ را بررسی کنید.</p><UButton :to="detailTarget(bug)" block color="neutral" :variant="actionable ? 'outline' : 'ghost'" :aria-label="`${reviewActionLabel(bug)} برای ${bug.public_id}`">{{ reviewActionLabel(bug) }}</UButton></li></ol>
  </div>
</template>

<style scoped>
.qa-ledger{border-top:1px solid var(--ui-border)}.qa-ledger__table{border-collapse:collapse;table-layout:fixed;width:100%}.qa-ledger__table th{color:var(--ui-text-muted);font-size:.72rem;font-weight:650;padding:.65rem .75rem;text-align:start}.qa-ledger__table td{border-top:1px solid var(--ui-border);font-size:.82rem;padding:.8rem .75rem;vertical-align:top}.qa-ledger__table th:nth-child(1){width:20%}.qa-ledger__table th:nth-child(2){width:12%}.qa-ledger__table th:nth-child(3){width:10%}.qa-ledger__table th:nth-child(4){width:14%}.qa-ledger__table th:nth-child(5){width:26%}.qa-ledger__table th:nth-child(6){width:10%}.qa-ledger__table th:nth-child(7){width:8%}.qa-ledger__table tr:hover td,.qa-ledger__table tr:focus-within td{background:var(--ui-bg-elevated)}.qa-ledger__classification{display:grid;gap:.1rem;margin:0}.qa-ledger__classification span,.qa-ledger__context span{color:var(--ui-text-muted);font-size:.68rem}.qa-ledger__classification--compact{display:none}.qa-ledger__attempt{align-items:flex-start;display:grid;gap:.35rem}.qa-ledger__attempt>span{color:var(--ui-text-muted);font-size:.75rem}.qa-ledger__context{display:grid;gap:.55rem}.qa-ledger__context p{display:grid;gap:.16rem;margin:0;min-width:0}.qa-ledger__context bdi{display:-webkit-box;line-height:1.55;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2}.qa-ledger__warning,.qa-ledger__warning bdi{color:var(--ui-warning)}.qa-ledger__row-warning{font-size:.72rem;margin:.5rem 0 0}.qa-ledger__duplicate{color:var(--ui-text-muted)}.qa-ledger__table time,.qa-ledger__mobile time{color:var(--ui-text-muted);font-size:.74rem;white-space:nowrap}.qa-ledger__mobile{display:none}@media(min-width:768px) and (max-width:1279px){.qa-ledger__classification-column{display:none}.qa-ledger__classification--compact{display:block;color:var(--ui-text-muted);font-size:.72rem;margin-top:.45rem}.qa-ledger__table th:nth-child(1){width:23%}.qa-ledger__table th:nth-child(2){width:16%}.qa-ledger__table th:nth-child(4){width:16%}.qa-ledger__table th:nth-child(5){width:28%}.qa-ledger__table th:nth-child(6){width:10%}.qa-ledger__table th:nth-child(7){width:7%}}@media(max-width:767px){.qa-ledger__table{display:none}.qa-ledger__mobile{display:grid;margin:0;padding:0}.qa-ledger__mobile li{border-top:1px solid var(--ui-border);display:grid;gap:.55rem;list-style:none;padding:1rem 0}.qa-ledger__mobile-classification{color:var(--ui-text-muted);font-size:.78rem;margin:0}.qa-ledger__mobile :deep(button),.qa-ledger__mobile :deep(a[class*=button]){min-height:2.75rem}}
</style>
