<script setup lang="ts">
import { ApiError } from '~/plugins/api.client'
import { adminErrorMessage, useAdministration, type AdminProject } from '~/composables/useAdministration'

definePageMeta({ middleware: 'auth' })
const admin = useAdministration()
const session = useSession()
const workspace = useWorkspace()
const route = useRoute()
const router = useRouter()
const project = ref<AdminProject | null>(null)
const loading = ref(true)
const error = ref('')
const editing = ref(false)
const deactivateOpen = ref(false)
const pending = ref(false)
const fieldErrors = ref<Record<string, string[]>>({})
const form = reactive({ name: '', key: '', description: '' })
const key = computed(() => String(route.params.key).toUpperCase())
const isSystemAdmin = computed(() => session.user.value?.is_system_admin || false)
const canManage = computed(() => isSystemAdmin.value || Boolean(project.value?.active && session.user.value?.memberships.some(membership => membership.active && membership.project.key === project.value?.key && membership.roles.includes('admin'))))
const currentRoles = computed(() => session.user.value?.memberships.find(membership => membership.active && membership.project.key === project.value?.key)?.roles || [])
async function load() { loading.value = true; error.value = ''; try { project.value = (await admin.getProject(key.value)).data; Object.assign(form, { name: project.value.name, key: project.value.key, description: project.value.description || '' }) } catch (caught) { error.value = adminErrorMessage(caught) } finally { loading.value = false } }
async function save() { if (!project.value || pending.value) return; pending.value = true; error.value = ''; fieldErrors.value = {}; const keyChanged = form.key.trim().toUpperCase() !== project.value.key; try { const result = await admin.updateProject(project.value.key, { name: form.name.trim(), key: form.key.trim().toUpperCase(), description: form.description.trim() || null }); project.value = result.data; editing.value = false; await workspace.refresh(); if (keyChanged) await router.replace(`/projects/${encodeURIComponent(result.data.key)}`) } catch (caught: any) { error.value = adminErrorMessage(caught); fieldErrors.value = caught?.fieldErrors || {} } finally { pending.value = false } }
async function deactivate() { if (!project.value || pending.value) return; pending.value = true; error.value = ''; try { project.value = (await admin.updateProject(project.value.key, { active: false })).data; deactivateOpen.value = false; await Promise.all([workspace.refresh(), session.refresh()]); if (!isSystemAdmin.value) await navigateTo('/projects') } catch (caught) { error.value = adminErrorMessage(caught) } finally { pending.value = false } }
await load()
</script>

<template>
  <main v-if="project" class="project-general"><ProjectSettingsHeader :project="project" :can-manage="canManage" /><section v-if="error" class="project-general__notice"><UAlert color="error" variant="subtle" :description="error" /></section><section class="project-general__body"><div class="project-general__heading"><div><h2>اطلاعات پروژه</h2><p>مشخصات و وضعیت ثبت‌شدهٔ پروژه.</p></div><UButton v-if="canManage && !editing" color="neutral" variant="outline" size="sm" @click="editing = true">ویرایش</UButton></div><form v-if="editing" class="project-general__form" @submit.prevent="save"><UFormField label="نام" :error="fieldErrors.name?.[0]"><UInput v-model="form.name" :disabled="pending" maxlength="150" /></UFormField><UFormField label="کلید" description="تغییر کلید، نشانی پروژه را تغییر می‌دهد." :error="fieldErrors.key?.[0]"><UInput v-model="form.key" dir="ltr" :disabled="pending" maxlength="20" /></UFormField><UFormField label="توضیحات"><UTextarea v-model="form.description" :disabled="pending" /></UFormField><div class="project-general__form-actions"><UButton color="neutral" variant="ghost" :disabled="pending" @click="editing = false">انصراف</UButton><UButton type="submit" :loading="pending">ذخیره تغییرات</UButton></div></form><dl v-else class="project-general__details"><div><dt>نام</dt><dd dir="auto">{{ project.name }}</dd></div><div><dt>کلید</dt><dd><TechnicalValue :value="project.key" /></dd></div><div><dt>توضیحات</dt><dd dir="auto">{{ project.description || 'بدون توضیحات' }}</dd></div><div><dt>وضعیت</dt><dd><UBadge :color="project.active ? 'success' : 'warning'" variant="subtle">{{ project.active ? 'فعال' : 'غیرفعال' }}</UBadge></dd></div><div><dt>دسترسی من</dt><dd><RoleBadges :roles="currentRoles" :system-admin="isSystemAdmin" :project-admin="canManage && !isSystemAdmin" /></dd></div></dl><UButton :to="{ path: '/bugs', query: { project: project.key } }" color="neutral" variant="outline">نمایش باگ‌های پروژه</UButton><section v-if="canManage && project.active" class="project-general__danger"><h2>وضعیت پروژه</h2><p>غیرفعال‌سازی فقط زمانی انجام می‌شود که همهٔ باگ‌های باز بسته شده باشند.</p><UButton color="error" variant="outline" @click="deactivateOpen = true">غیرفعال‌کردن پروژه</UButton></section><details class="project-general__technical"><summary>شناسهٔ فنی</summary><TechnicalValue :value="project.id" /></details></section></main>
  <main v-else class="project-unavailable"><section v-if="loading" aria-busy="true"><USkeleton class="h-8 w-48" /><USkeleton class="mt-6 h-44 w-full" /></section><UAlert v-else color="error" variant="subtle" title="پروژه پیدا نشد یا دیگر در دسترس شما نیست." :description="error"><template #actions><UButton to="/projects" size="xs" color="neutral" variant="outline">پروژه‌ها</UButton><UButton size="xs" color="error" variant="outline" @click="load">تلاش مجدد</UButton></template></UAlert></main>
  <UModal :open="deactivateOpen" title="غیرفعال‌کردن پروژه" description="پروژه و تاریخچهٔ آن حفظ می‌شود، اما اعضا دیگر آن را نمی‌بینند و مدیریت پروژه‌ای متوقف می‌شود." @update:open="value => { if (!pending) deactivateOpen = value }"><template #body><UAlert v-if="error" color="error" variant="subtle" :description="error" /><p>همهٔ باگ‌های غیرِبسته باید ابتدا حل و بسته شوند. شمارش پیشاپیش در دسترس نیست.</p><UButton v-if="error.includes('open bug')" :to="{ path: '/bugs', query: { project: project?.key, status: 'submitted,review,needs_information,assigned,in_progress,resolved,qa_verification,reopened' } }" color="neutral" variant="outline">نمایش باگ‌های باز</UButton></template><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="deactivateOpen = false">انصراف</UButton><UButton color="error" :loading="pending" @click="deactivate">غیرفعال‌کردن پروژه</UButton></template></UModal>
</template>

<style scoped>
.project-general__notice{padding:1rem 1.5rem 0}.project-general__body{max-width:70rem;padding:1.5rem}.project-general__heading{align-items:flex-start;display:flex;justify-content:space-between;margin-bottom:1rem}.project-general h2{font-size:1rem;margin:0}.project-general__heading p,.project-general__danger p{color:var(--ui-text-muted);font-size:.84rem;margin:.3rem 0 0}.project-general__details{display:grid;gap:1rem;grid-template-columns:repeat(2,minmax(0,1fr));margin:0 0 1.25rem}.project-general__details div{border-bottom:1px solid var(--ui-border);padding-bottom:.75rem}.project-general dt{color:var(--ui-text-muted);font-size:.75rem}.project-general dd{margin:.3rem 0 0}.project-general__form{display:grid;gap:1rem;margin-bottom:1rem}.project-general__form-actions{display:flex;gap:.5rem}.project-general__danger{border-top:1px solid var(--ui-border);margin-top:2rem;padding-top:1.25rem}.project-general__danger .button{margin-top:.9rem}.project-general__technical{color:var(--ui-text-muted);font-size:.8rem;margin-top:1.5rem}.project-general__technical :deep(bdi){display:block;margin-top:.5rem}.project-unavailable{padding:1.5rem}@media(max-width:767px){.project-general__body{padding:1rem}.project-general__notice{padding:1rem 1rem 0}.project-general__details{grid-template-columns:1fr}}
</style>
