<script setup lang="ts">
import { ApiError } from '~/plugins/api.client'
import { adminErrorMessage, useAdministration, type AdminMembership, type AdminProject } from '~/composables/useAdministration'
import { roleLabel } from '~/utils/presentation'

definePageMeta({ middleware: 'auth' })
const admin = useAdministration()
const session = useSession()
const route = useRoute()
const project = ref<AdminProject | null>(null)
const memberships = ref<AdminMembership[]>([])
const loading = ref(true)
const error = ref('')
const pending = ref(false)
const search = ref('')
const state = ref<'all' | 'active' | 'inactive'>('all')
const createOpen = ref(false)
const editTarget = ref<AdminMembership | null>(null)
const stateTarget = ref<AdminMembership | null>(null)
const remediation = ref<{ membership: AdminMembership; data: { active?: boolean; roles?: string[] }; message: string } | null>(null)
const replacementId = ref('')
const fieldErrors = ref<Record<string, string[]>>({})
const memberForm = reactive({ user_id: '', roles: ['reporter'] as string[] })
const editRoles = ref<string[]>([])
const allRoles = ['reporter', 'developer', 'qa', 'admin']
const key = computed(() => String(route.params.key).toUpperCase())
const systemAdmin = computed(() => session.user.value?.is_system_admin || false)
const canManage = computed(() => systemAdmin.value || Boolean(project.value?.active && session.user.value?.memberships.some(m => m.active && m.project.key === project.value?.key && m.roles.includes('admin'))))
const rows = computed(() => memberships.value.filter(member => (!search.value.trim() || `${member.user_display_name} ${member.user_id}`.toLowerCase().includes(search.value.trim().toLowerCase())) && (state.value === 'all' || (state.value === 'active') === member.active)))
const candidates = computed(() => memberships.value.filter(member => member.active && member.roles.includes('developer') && member.id !== remediation.value?.membership.id))
const affectedBugIds = computed(() => remediation.value?.message.match(/BUG-\d+/g) || [])
function canDeactivate(member: AdminMembership) { return systemAdmin.value || !member.roles.includes('admin') }
function lockedAdmin(member: AdminMembership | null) { return Boolean(member?.roles.includes('admin') && !systemAdmin.value) }
function roleInputDisabled(role: string, member?: AdminMembership) { return pending.value || (role === 'admin' && !systemAdmin.value) || Boolean(member && role === 'admin' && lockedAdmin(member)) }
async function load() { loading.value = true; error.value = ''; try { project.value = (await admin.getProject(key.value)).data; if (!canManage.value) { error.value = 'دسترسی فعلی شما برای مدیریت اعضا کافی نیست.'; return } memberships.value = (await admin.listMemberships(project.value.key)).data } catch (caught) { error.value = adminErrorMessage(caught) } finally { loading.value = false } }
function openEdit(member: AdminMembership) { editTarget.value = member; editRoles.value = [...member.roles] }
async function create() { if (!project.value || pending.value) return; pending.value = true; error.value = ''; fieldErrors.value = {}; try { await admin.createMembership(project.value.key, { user_id: memberForm.user_id.trim(), roles: [...memberForm.roles] }); createOpen.value = false; Object.assign(memberForm, { user_id: '', roles: ['reporter'] }); await load() } catch (caught: any) { error.value = adminErrorMessage(caught); fieldErrors.value = caught?.fieldErrors || {} } finally { pending.value = false } }
async function saveRoles() { const member = editTarget.value; if (!member || pending.value) return; const roles = [...editRoles.value]; if (lockedAdmin(member) && !roles.includes('admin')) roles.push('admin'); await attempt(member, { roles }); editTarget.value = null }
async function changeState(member: AdminMembership) { await attempt(member, { active: !member.active }); stateTarget.value = null }
async function attempt(member: AdminMembership, data: { active?: boolean; roles?: string[] }, remediationData?: { unassign: true } | { reassign_to: string }) { if (pending.value) return; pending.value = true; error.value = ''; try { await admin.updateMembership(member.id, remediationData ? { ...data, remediation: remediationData } : data); remediation.value = null; await load() } catch (caught) { const message = adminErrorMessage(caught); error.value = message; if (caught instanceof ApiError && caught.status === 409) remediation.value = { membership: member, data, message } } finally { pending.value = false } }
async function remediate(data: { unassign: true } | { reassign_to: string }) { if (remediation.value) await attempt(remediation.value.membership, remediation.value.data, data) }
await load()
</script>

<template>
  <main v-if="project" class="project-members"><ProjectSettingsHeader :project="project" :can-manage="canManage" /><section v-if="!canManage" class="project-members__state"><UAlert color="warning" variant="subtle" title="مدیریت اعضا در دسترس نیست" description="فقط مدیر پروژه در دامنهٔ فعال یا مدیر سراسری می‌تواند اعضا و نقش‌ها را ببیند." /></section><template v-else><section class="project-members__toolbar"><div><h2>اعضا و نقش‌ها</h2><p>عضویت و نقش‌ها فقط برای همین پروژه مدیریت می‌شوند.</p></div><UButton size="sm" icon="i-lucide-user-plus" @click="createOpen = true">افزودن عضو</UButton></section><section class="project-members__filters"><UInput v-model="search" icon="i-lucide-search" placeholder="جست‌وجوی نام یا شناسهٔ کاربر…" /><USelect v-model="state" :items="[{ label: 'همه', value: 'all' }, { label: 'فعال', value: 'active' }, { label: 'غیرفعال', value: 'inactive' }]" /></section><section v-if="loading" class="project-members__loading" aria-busy="true"><USkeleton v-for="index in 6" :key="index" class="h-14 w-full" /></section><section v-else-if="error" class="project-members__state"><UAlert color="error" variant="subtle" title="بارگیری اعضا انجام نشد" :description="error"><template #actions><UButton size="xs" color="error" variant="outline" @click="load">تلاش مجدد</UButton></template></UAlert></section><section v-else-if="!memberships.length" class="project-members__state"><h2>هنوز عضوی وجود ندارد.</h2><UButton size="sm" @click="createOpen = true">افزودن عضو</UButton></section><section v-else-if="!rows.length" class="project-members__state"><h2>عضوی با این جست‌وجو وجود ندارد.</h2><UButton size="sm" color="neutral" variant="ghost" @click="search = ''; state = 'all'">پاک‌کردن جست‌وجو</UButton></section><div v-else class="project-members__table-wrap"><table class="project-members__table"><thead><tr><th>کاربر</th><th>نقش‌ها</th><th>وضعیت عضویت</th><th><span class="sr-only">اقدام</span></th></tr></thead><tbody><tr v-for="member in rows" :key="member.id"><td><UserIdentity :name="member.user_display_name" :user-id="member.user_id" /></td><td><RoleBadges :roles="member.roles" :project-admin="member.roles.includes('admin')" /></td><td><UBadge :color="member.active ? 'success' : 'warning'" variant="subtle">{{ member.active ? 'فعال' : 'غیرفعال' }}</UBadge></td><td class="project-members__actions"><UButton size="xs" color="neutral" variant="ghost" @click="openEdit(member)">ویرایش نقش‌ها</UButton><UButton v-if="member.active && canDeactivate(member)" size="xs" color="error" variant="ghost" @click="stateTarget = member">غیرفعال‌کردن</UButton><UButton v-else-if="!member.active" size="xs" color="neutral" variant="ghost" @click="stateTarget = member">فعال‌کردن دوباره</UButton></td></tr></tbody></table></div></template></main>
  <main v-else class="project-members__state"><USkeleton v-if="loading" class="h-40 w-full" /><UAlert v-else color="error" variant="subtle" title="پروژه پیدا نشد یا در دسترس نیست." :description="error" /></main>
  <UModal :open="createOpen" title="افزودن عضو" description="کاربر باید از قبل در BugSense وجود داشته باشد؛ این فرایند دعوت‌نامه نیست." @update:open="value => { if (!pending) createOpen = value }"><template #body><UAlert v-if="error" color="error" variant="subtle" :description="error" class="mb-4" /><form class="member-form" @submit.prevent="create"><UFormField label="شناسهٔ کاربر" :error="fieldErrors.user_id?.[0]"><UInput v-model="memberForm.user_id" dir="ltr" placeholder="UUID" :disabled="pending" /></UFormField><fieldset><legend>نقش‌ها</legend><label v-for="role in allRoles" v-show="role !== 'admin' || systemAdmin" :key="role"><input v-model="memberForm.roles" type="checkbox" :value="role" :disabled="roleInputDisabled(role)"> {{ role === 'admin' ? 'مدیر پروژه' : role }}</label></fieldset></form></template><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="createOpen = false">انصراف</UButton><UButton :loading="pending" :disabled="!memberForm.roles.length" @click="create">افزودن عضو</UButton></template></UModal>
  <UModal :open="!!editTarget" title="ویرایش نقش‌ها" description="همهٔ نقش‌های انتخاب‌شده به‌صورت یک مجموعه ذخیره می‌شوند." @update:open="value => { if (!value && !pending) editTarget = null }"><template #body><RoleBadges v-if="editTarget" :roles="editTarget.roles" :project-admin="editTarget.roles.includes('admin')" class="mb-4" /><fieldset class="member-form"><legend>نقش‌ها</legend><label v-for="role in allRoles" v-show="role !== 'admin' || systemAdmin || editTarget?.roles.includes('admin')" :key="role"><input v-model="editRoles" type="checkbox" :value="role" :disabled="roleInputDisabled(role, editTarget || undefined)"> {{ role === 'admin' ? 'مدیر پروژه' : role }}<small v-if="role === 'admin' && !systemAdmin">فقط مدیر سراسری می‌تواند نقش مدیر پروژه را تغییر دهد.</small></label></fieldset></template><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="editTarget = null">انصراف</UButton><UButton :loading="pending" @click="saveRoles">ذخیره نقش‌ها</UButton></template></UModal>
  <UModal :open="!!stateTarget" :title="stateTarget?.active ? 'غیرفعال‌کردن عضویت' : 'فعال‌کردن دوبارهٔ عضویت'" @update:open="value => { if (!value && !pending) stateTarget = null }"><template #body><p v-if="stateTarget?.active">رکورد عضویت حذف نمی‌شود. ممکن است برای واگذاری‌های باز، اصلاح از سوی سرور لازم باشد.</p><p v-else>همان رکورد تاریخی و نقش‌های فعال آن بازگردانده می‌شود.</p></template><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="stateTarget = null">انصراف</UButton><UButton :color="stateTarget?.active ? 'error' : 'primary'" :loading="pending" @click="stateTarget && changeState(stateTarget)">{{ stateTarget?.active ? 'غیرفعال‌کردن' : 'فعال‌کردن دوباره' }}</UButton></template></UModal>
  <UModal :open="!!remediation" title="اصلاح واگذاری‌های باز" :description="remediation?.message" @update:open="value => { if (!value && !pending) remediation = null }"><template #body><p>یک انتخاب برای همهٔ واگذاری‌های باز اعمال می‌شود؛ انتخاب جداگانه برای هر باگ پشتیبانی نمی‌شود.</p><USelect v-if="candidates.length" :items="candidates.map(member => ({ label: member.user_display_name, value: member.user_id }))" placeholder="توسعه‌دهندهٔ جایگزین" @update:model-value="value => { if (value) remediate({ reassign_to: String(value) }) }" /><UAlert v-else color="warning" variant="subtle" description="توسعه‌دهندهٔ فعال دیگری در این پروژه برای جایگزینی در دسترس نیست." /></template><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="remediation = null">انصراف</UButton><UButton color="error" :loading="pending" @click="remediate({ unassign: true })">لغو تخصیص و بازگشت به بررسی</UButton></template></UModal>
</template>

<style scoped>
.project-members__toolbar,.project-members__filters{align-items:center;border-bottom:1px solid var(--ui-border);display:flex;gap:1rem;justify-content:space-between;padding:1rem 1.5rem}.project-members__toolbar h2{font-size:1rem;margin:0}.project-members__toolbar p{color:var(--ui-text-muted);font-size:.82rem;margin:.25rem 0 0}.project-members__filters{justify-content:flex-start}.project-members__filters :deep(input){min-width:18rem}.project-members__loading,.project-members__state{display:grid;gap:.65rem;margin:1.25rem 1.5rem}.project-members__state h2{font-size:1rem;margin:0}.project-members__table-wrap{padding:0 1.5rem}.project-members__table{border-collapse:collapse;table-layout:fixed;width:100%}.project-members__table th{color:var(--ui-text-muted);font-size:.72rem;font-weight:650;padding:.65rem .75rem;text-align:start}.project-members__table td{border-top:1px solid var(--ui-border);font-size:.83rem;padding:.8rem .75rem;vertical-align:top}.project-members__table th:nth-child(1){width:35%}.project-members__table th:nth-child(2){width:30%}.project-members__table th:nth-child(3){width:15%}.project-members__table th:nth-child(4){width:20%}.project-members__actions{display:flex;flex-wrap:wrap;gap:.25rem}.member-form{display:grid;gap:.8rem}.member-form fieldset,.member-form{border:0;margin:0;padding:0}.member-form label{align-items:start;display:flex;gap:.4rem}.member-form small{color:var(--ui-text-muted);display:block;font-size:.72rem}@media(max-width:767px){.project-members__toolbar,.project-members__filters{align-items:stretch;flex-direction:column;padding-inline:1rem}.project-members__filters :deep(input){min-width:0}.project-members__table-wrap{padding:0 1rem}.project-members__table th:nth-child(3),.project-members__table td:nth-child(3){display:none}.project-members__table th:nth-child(1){width:38%}.project-members__table th:nth-child(2){width:32%}.project-members__table th:nth-child(4){width:30%}}
</style>
