<script setup lang="ts">
import { ApiError } from '~/plugins/api.client'
import { adminErrorMessage, useAdministration, type AdminProject, type AdminTrackingValue, type TrackingKind } from '~/composables/useAdministration'
import { trackingKindLabel } from '~/utils/presentation'

definePageMeta({ middleware: 'auth' })
const admin = useAdministration()
const session = useSession()
const route = useRoute()
const project = ref<AdminProject | null>(null)
const values = ref<AdminTrackingValue[]>([])
const loading = ref(true)
const error = ref('')
const pending = ref(false)
const kind = ref<TrackingKind>('category')
const search = ref('')
const state = ref<'all' | 'active' | 'inactive'>('active')
const createOpen = ref(false)
const editTarget = ref<AdminTrackingValue | null>(null)
const deactivateTarget = ref<AdminTrackingValue | null>(null)
const remediation = ref<{ value: AdminTrackingValue; message: string } | null>(null)
const fieldErrors = ref<Record<string, string[]>>({})
const form = reactive({ code: '', name: '', rank: '' })
const kinds: TrackingKind[] = ['category', 'priority', 'severity', 'tag', 'resolution_label']
const key = computed(() => String(route.params.key).toUpperCase())
const systemAdmin = computed(() => session.user.value?.is_system_admin || false)
const canManage = computed(() => systemAdmin.value || Boolean(project.value?.active && session.user.value?.memberships.some(m => m.active && m.project.key === project.value?.key && m.roles.includes('admin'))))
const currentRows = computed(() => values.value.filter(value => value.kind === kind.value && (!search.value.trim() || `${value.name} ${value.code}`.toLowerCase().includes(search.value.trim().toLowerCase())) && (state.value === 'all' || (state.value === 'active') === value.active)))
const replacements = computed(() => values.value.filter(value => value.active && value.kind === remediation.value?.value.kind && value.id !== remediation.value?.value.id))
async function load() { loading.value = true; error.value = ''; try { project.value = (await admin.getProject(key.value)).data; values.value = (await admin.listTrackingValues(project.value.key)).data } catch (caught) { error.value = adminErrorMessage(caught) } finally { loading.value = false } }
function resetForm() { Object.assign(form, { code: '', name: '', rank: '' }) }
async function create() { if (!project.value || pending.value) return; pending.value = true; fieldErrors.value = {}; error.value = ''; try { await admin.createTrackingValue(project.value.key, { kind: kind.value, code: form.code.trim(), name: form.name.trim(), rank: form.rank === '' ? null : Number(form.rank) }); createOpen.value = false; resetForm(); await load() } catch (caught: any) { error.value = adminErrorMessage(caught); fieldErrors.value = caught?.fieldErrors || {} } finally { pending.value = false } }
function openEdit(value: AdminTrackingValue) { editTarget.value = value; Object.assign(form, { code: value.code, name: value.name, rank: String(value.rank ?? '') }) }
async function saveEdit() { const value = editTarget.value; if (!value || pending.value) return; pending.value = true; fieldErrors.value = {}; error.value = ''; try { await admin.updateTrackingValue(value.id, { name: form.name.trim(), rank: form.rank === '' ? null : Number(form.rank) }); editTarget.value = null; resetForm(); await load() } catch (caught: any) { error.value = adminErrorMessage(caught); fieldErrors.value = caught?.fieldErrors || {} } finally { pending.value = false } }
async function updateState(value: AdminTrackingValue, active: boolean, remediationData?: { unset: true } | { replace_with: string }) { if (pending.value) return; pending.value = true; error.value = ''; try { await admin.updateTrackingValue(value.id, remediationData ? { active, remediation: remediationData } : { active }); deactivateTarget.value = null; remediation.value = null; await load() } catch (caught) { const message = adminErrorMessage(caught); error.value = message; if (caught instanceof ApiError && caught.status === 409) remediation.value = { value, message } } finally { pending.value = false } }
await load()
</script>

<template>
  <main v-if="project" class="project-tracking"><ProjectSettingsHeader :project="project" :can-manage="canManage" /><section class="project-tracking__toolbar"><div><h2>مقادیر پیگیری</h2><p>همهٔ مقادیر فقط در همین پروژه کاربرد دارند.</p></div><UButton v-if="canManage" size="sm" icon="i-lucide-plus" @click="createOpen = true">افزودن مقدار</UButton></section><section class="project-tracking__kinds" aria-label="نوع مقدار"><UButton v-for="item in kinds" :key="item" size="xs" :color="kind === item ? 'primary' : 'neutral'" :variant="kind === item ? 'soft' : 'ghost'" @click="kind = item">{{ trackingKindLabel(item) }}</UButton></section><section class="project-tracking__filters"><UInput v-model="search" icon="i-lucide-search" placeholder="جست‌وجوی نام یا کد…" /><USelect v-model="state" :items="[{ label: 'فعال', value: 'active' }, { label: 'غیرفعال', value: 'inactive' }, { label: 'همه', value: 'all' }]" /></section><p v-if="kind === 'resolution_label'" class="project-tracking__note">این برچسب‌ها در مدیریت پروژه پشتیبانی می‌شوند؛ کاربرد مستقیمی در گردش‌کار فعلی نمایش داده نشده است.</p><section v-if="loading" class="project-tracking__loading" aria-busy="true"><USkeleton v-for="index in 6" :key="index" class="h-14 w-full" /></section><section v-else-if="error" class="project-tracking__state"><UAlert color="error" variant="subtle" title="بارگیری مقادیر انجام نشد" :description="error"><template #actions><UButton size="xs" color="error" variant="outline" @click="load">تلاش مجدد</UButton></template></UAlert></section><section v-else-if="!currentRows.length" class="project-tracking__state"><h2>برای این پروژه هنوز {{ trackingKindLabel(kind) }} تعریف نشده است.</h2><p v-if="!canManage">فقط مدیر مجاز می‌تواند مقدار جدیدی اضافه کند.</p><UButton v-if="canManage" size="sm" @click="createOpen = true">افزودن مقدار</UButton></section><div v-else class="project-tracking__table-wrap"><table class="project-tracking__table"><thead><tr><th>نام</th><th>کد</th><th>رتبه</th><th>وضعیت</th><th><span class="sr-only">اقدام</span></th></tr></thead><tbody><tr v-for="value in currentRows" :key="value.id"><td dir="auto"><strong>{{ value.name }}</strong></td><td><TechnicalValue :value="value.code" /></td><td>{{ value.rank ?? '—' }}</td><td><UBadge :color="value.active ? 'success' : 'warning'" variant="subtle">{{ value.active ? 'فعال' : 'غیرفعال' }}</UBadge></td><td class="project-tracking__actions"><UButton v-if="canManage" size="xs" color="neutral" variant="ghost" @click="openEdit(value)">ویرایش</UButton><UButton v-if="canManage && value.active" size="xs" color="error" variant="ghost" @click="deactivateTarget = value">غیرفعال‌کردن</UButton><UButton v-else-if="canManage" size="xs" color="neutral" variant="ghost" @click="updateState(value, true)">فعال‌کردن دوباره</UButton></td></tr></tbody></table></div></main>
  <main v-else class="project-tracking__state"><USkeleton v-if="loading" class="h-40 w-full" /><UAlert v-else color="error" variant="subtle" title="پروژه پیدا نشد یا در دسترس نیست." :description="error" /></main>
  <UModal :open="createOpen" :title="`افزودن ${trackingKindLabel(kind)}`" @update:open="value => { if (!pending) createOpen = value }"><template #body><UAlert v-if="error" color="error" variant="subtle" :description="error" class="mb-4" /><form class="tracking-form" @submit.prevent="create"><UFormField label="نوع"><p>{{ trackingKindLabel(kind) }}</p></UFormField><UFormField label="نام" :error="fieldErrors.name?.[0]"><UInput v-model="form.name" :disabled="pending" /></UFormField><UFormField label="کد" :error="fieldErrors.code?.[0]"><UInput v-model="form.code" dir="ltr" :disabled="pending" /></UFormField><UFormField label="رتبه" description="اختیاری؛ عدد صحیح نامنفی."><UInput v-model="form.rank" type="number" min="0" :disabled="pending" /></UFormField></form></template><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="createOpen = false">انصراف</UButton><UButton :loading="pending" @click="create">افزودن مقدار</UButton></template></UModal>
  <UModal :open="!!editTarget" title="ویرایش مقدار" @update:open="value => { if (!value && !pending) editTarget = null }"><template #body><form class="tracking-form" @submit.prevent="saveEdit"><UFormField label="نوع"><p>{{ editTarget && trackingKindLabel(editTarget.kind) }}</p></UFormField><UFormField label="کد"><TechnicalValue v-if="editTarget" :value="editTarget.code" /></UFormField><UFormField label="نام" :error="fieldErrors.name?.[0]"><UInput v-model="form.name" :disabled="pending" /></UFormField><UFormField label="رتبه" :error="fieldErrors.rank?.[0]"><UInput v-model="form.rank" type="number" min="0" :disabled="pending" /></UFormField></form></template><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="editTarget = null">انصراف</UButton><UButton :loading="pending" @click="saveEdit">ذخیره</UButton></template></UModal>
  <UModal :open="!!deactivateTarget" title="غیرفعال‌کردن مقدار" description="رکورد حذف نمی‌شود؛ ممکن است برای باگ‌های باز به اصلاح نیاز باشد." @update:open="value => { if (!value && !pending) deactivateTarget = null }"><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="deactivateTarget = null">انصراف</UButton><UButton color="error" :loading="pending" @click="deactivateTarget && updateState(deactivateTarget, false)">غیرفعال‌کردن</UButton></template></UModal>
  <UModal :open="!!remediation" title="اصلاح مقادیر باگ‌های باز" :description="remediation?.message" @update:open="value => { if (!value && !pending) remediation = null }"><template #body><p>انتخاب شما برای همهٔ باگ‌های بازِ متأثر اعمال می‌شود؛ باگ‌های بسته مقدار تاریخی را نگه می‌دارند.</p><USelect v-if="replacements.length" :items="replacements.map(value => ({ label: value.name, value: value.id }))" placeholder="مقدار فعال جایگزین" @update:model-value="value => { if (value && remediation) updateState(remediation.value, false, { replace_with: String(value) }) }" /></template><template #footer><UButton color="neutral" variant="ghost" :disabled="pending" @click="remediation = null">انصراف</UButton><UButton color="error" :loading="pending" @click="remediation && updateState(remediation.value, false, { unset: true })">حذف مقدار از باگ‌های باز</UButton></template></UModal>
</template>

<style scoped>
.project-tracking__toolbar,.project-tracking__filters{align-items:center;border-bottom:1px solid var(--ui-border);display:flex;gap:1rem;justify-content:space-between;padding:1rem 1.5rem}.project-tracking__toolbar h2{font-size:1rem;margin:0}.project-tracking__toolbar p,.project-tracking__note,.project-tracking__state p{color:var(--ui-text-muted);font-size:.82rem;margin:.25rem 0 0}.project-tracking__kinds{border-bottom:1px solid var(--ui-border);display:flex;gap:.25rem;overflow:auto;padding:.5rem 1.5rem}.project-tracking__kinds button{white-space:nowrap}.project-tracking__filters{justify-content:flex-start}.project-tracking__filters :deep(input){min-width:18rem}.project-tracking__note{margin:1rem 1.5rem}.project-tracking__loading,.project-tracking__state{display:grid;gap:.65rem;margin:1.25rem 1.5rem}.project-tracking__state h2{font-size:1rem;margin:0}.project-tracking__table-wrap{padding:0 1.5rem}.project-tracking__table{border-collapse:collapse;table-layout:fixed;width:100%}.project-tracking__table th{color:var(--ui-text-muted);font-size:.72rem;font-weight:650;padding:.65rem .75rem;text-align:start}.project-tracking__table td{border-top:1px solid var(--ui-border);font-size:.83rem;padding:.8rem .75rem;vertical-align:top}.project-tracking__table th:nth-child(1){width:32%}.project-tracking__table th:nth-child(2){width:25%}.project-tracking__table th:nth-child(3){width:12%}.project-tracking__table th:nth-child(4){width:14%}.project-tracking__table th:nth-child(5){width:17%}.project-tracking__actions{display:flex;flex-wrap:wrap;gap:.25rem}.tracking-form{display:grid;gap:1rem}@media(max-width:767px){.project-tracking__toolbar,.project-tracking__filters{align-items:stretch;flex-direction:column;padding-inline:1rem}.project-tracking__kinds{padding-inline:1rem}.project-tracking__filters :deep(input){min-width:0}.project-tracking__note,.project-tracking__loading,.project-tracking__state{margin-inline:1rem}.project-tracking__table-wrap{padding:0 1rem}.project-tracking__table th:nth-child(3),.project-tracking__table td:nth-child(3){display:none}.project-tracking__table th:nth-child(1){width:35%}.project-tracking__table th:nth-child(2){width:27%}.project-tracking__table th:nth-child(4){width:18%}.project-tracking__table th:nth-child(5){width:20%}}
</style>
